### ISSUE TITLE
CR/LF에 대해서..

### ISSUE THREAD

**Issue by ywen407** [NamsooCho/Crawler_2#7]
os 플랫폼마다 CR/LF가 개행문자 인식이 다른데.. 

- Windows의경우 CR/LF

- mac,linux의경우 LF

개행문자 인식이 달라서 pull request할때 보통 LF로 맞추는것 같더라구요. 
어떻게 따로 설정을 해야되는건가요? 
CR/LF를 추가하라고 하셔서 그냥 엔터 두번 딱딱 해놓긴 했는데..

**Comment by NamsooCho** [comment]
그냥 파일의 마지막에 빈 행을 하나 두시라는 의미입니다.

**Comment by NamsooCho** [comment]
제가 코멘트한것이 너무 확대 해석된거 같습니다. :D

**Comment by NamsooCho** [comment]
이 이슈는 닫으셔도 될듯....

**Comment by ywen407** [comment]
네 알겠습니다 감사합니다~
